# Documento de Visão – Sistema de Gerenciamento de Inadimplentes

## 05 de setembro de 2025

O projeto de desenvolvimento proposto pelo aluno **Matheus Pereira** para o Trabalho de Conclusão de Curso (TCC) do curso de Bacharelado em Engenharia de Software da Pontifícia Universidade Católica de Minas Gerais (PUC Minas) tem como objetivo a criação de um sistema de software para **gerenciamento de clientes inadimplentes** em um escritório de contabilidade localizado no interior de Minas Gerais. O propósito do sistema é apoiar a área financeira do escritório, oferecendo uma ferramenta automatizada que permita registrar pagamentos, controlar saldos devedores e gerar relatórios consolidados de inadimplência, garantindo maior precisão, segurança e eficiência na gestão de informações financeiras.

Em acordo com os itens 3.2.2 e 3.2.2.1 da Resolução de TCC I, que definem, respectivamente, que "trabalhos de desenvolvimento que possuam cliente específico devem ser formalizados com carta de interesse e contratos institucionais" e que "trabalhos de desenvolvimento para clientes externos devem atender às demandas reais identificadas pelo cliente", este trabalho enquadra-se no **caso de sistema a ser desenvolvido para cliente real**. Para tanto, será enviada uma carta de interesse ao Coordenador das Unidades Curriculares de TCC (cleitontavares@pucminas.br) e à Coordenação do Curso de Engenharia de Software (engsoftware.lourdes@pucminas.br), formalizando o desejo do escritório de contabilidade de implementar uma solução tecnológica para otimizar o controle de inadimplência. A autorização para o desenvolvimento do TCC será condicionada à análise da carta e à assinatura dos contratos institucionais.

Atualmente, o escritório realiza o controle da inadimplência de forma **manual**, registrando os dados dos clientes e seus respectivos pagamentos em cadernos. Esse método, embora simples, apresenta diversos problemas: aumenta a chance de erros, dificulta a atualização em tempo real, compromete a segurança das informações e torna complexa a geração de relatórios confiáveis. Além disso, não permite acompanhamento histórico adequado nem emissão de alertas sobre clientes com débitos em aberto, o que limita a capacidade do responsável financeiro de tomar decisões rápidas e precisas.

O sistema proposto tem como objetivo **automatizar e simplificar** o gerenciamento da inadimplência, concentrando as seguintes funcionalidades principais: cadastro de clientes inadimplentes, registro de pagamentos realizados, atualização automática do saldo devedor, geração de relatórios detalhados por cliente ou período e emissão de alertas para clientes com débitos pendentes. Todo o acesso será restrito ao responsável financeiro do escritório, garantindo a **segurança e sigilo das informações**, de acordo com as normas legais e éticas aplicáveis à área contábil.

O desenvolvimento do sistema segue princípios de **engenharia de software orientada à automação e eficiência**, buscando racionalizar recursos e otimizar processos operacionais. A solução será implementada em ambiente Windows, com autenticação por usuário e senha, garantindo que apenas o responsável financeiro tenha acesso aos dados. Adicionalmente, serão previstos mecanismos de backup periódico para assegurar a integridade das informações e prevenir perda de dados, atendendo às restrições definidas para sistemas críticos de gestão financeira.

Para a definição das funcionalidades, o projeto considerou três necessidades principais:  
1. **Controle confiável da inadimplência**, que elimina erros inerentes ao registro manual;  
2. **Visualização rápida do saldo devedor de cada cliente**, permitindo decisões e cobranças mais ágeis;  
3. **Geração de relatórios periódicos**, oferecendo uma visão global da inadimplência para planejamento estratégico e tomada de decisão.  

Cada uma dessas necessidades foi traduzida em funcionalidades concretas, categorizadas de acordo com sua criticidade, de modo a priorizar o que é essencial para o funcionamento do sistema desde a primeira versão.

O sistema não prevê, nesta versão inicial, integração com sistemas bancários para baixa automática de boletos, envio de notificações automáticas aos clientes devedores, emissão de notas fiscais ou acesso aos clientes finais. Estes pontos foram analisados, mas ficaram de fora do escopo com o objetivo de manter a solução **simples, de baixo custo e voltada exclusivamente ao uso interno** do escritório. Futuras versões poderão contemplar essas funcionalidades conforme necessidade do cliente.

Em termos de documentação, o sistema contará com um **manual do usuário** detalhando operações básicas, como cadastro de clientes, atualização de pagamentos e geração de relatórios; um **help online**, com perguntas frequentes e instruções rápidas para uso diário; um **guia de instalação**, explicando passo a passo como configurar o sistema no computador do escritório; e um **arquivo README**, reunindo informações técnicas e requisitos mínimos para operação adequada.

A proposta deste trabalho contribui diretamente para a **racionalização de recursos e melhoria da eficiência** no controle de inadimplentes, permitindo que o escritório de contabilidade otimize seu processo de gerenciamento financeiro e reduza erros que poderiam gerar prejuízos. Além disso, o projeto está alinhado às exigências acadêmicas da PUC Minas, proporcionando experiência prática em desenvolvimento de software orientado a clientes reais, implementação de sistemas seguros e confiáveis, e aplicação de princípios de engenharia de software em cenários reais de negócios.

Por fim, este trabalho permite que o aluno aplique conhecimentos adquiridos nas disciplinas de **Arquitetura de Software**, **Gerência de Configuração e Evolução de Software**, **Projeto de Software** e **Desenvolvimento de Aplicações Distribuídas**, integrando teoria e prática para a criação de uma solução que oferece **benefícios concretos para o cliente** e cumpre integralmente os requisitos da Resolução de TCC I, garantindo relevância acadêmica e aplicação prática.
